workspace = 1, monitor:DP-3, persistent:true, layout:master
workspace = 2, monitor:DP-3, persistent:true, layout:master
workspace = 3, monitor:DP-3, persistent:true, layout:master
workspace = 4, monitor:DP-3, persistent:true, layout:master
workspace = 5, monitor:DP-3, persistent:true, layout:master
workspace = 29, monitor:DP-3, defaultName:steam, layout:scrolling
workspace = 30, monitor:DP-3, defaultName:games, layout:monocle

workspace = 6, monitor:DP-2, persistent:true, layout:master
workspace = 7, monitor:DP-2, persistent:true, layout:master
workspace = 8, monitor:DP-2, persistent:true, layout:master
workspace = 9, monitor:DP-2, persistent:true, layout:master
workspace = 10, monitor:DP-2, persistent:true, layout:master
workspace = 31, monitor:DP-2, defaultName:discord, layout:scrolling, gapsout:10
workspace = 32, monitor:DP-2, defaultName:music, layout:master
